### ISSUE TITLE
start + inCluster flag do not work as expected

### ISSUE THREAD

**Issue by jonkerj** [plunder-app/kube-vip#108]
I am trying to run `kube-vip start` inside my cluster to have my CP become reachable on a VIP. I do not need any LB for now, just to have one of the nodes bind to the VIP and fight over it through leader election.

I start `kube-vip` (from a DaemonSet) in this cluster like this:
```
image: plndr/kube-vip:0.2.1
imagePullPolicy: Always
name: kube-vip
command:
- /kube-vip
- start
env:
  - name: vip_address
    value: "10.8.95.3"
  - name: vip_leaderelection
    value: "true"
  - name: vip_interface
    value: "eth0"
  - name: vip_loglevel
    value: "5"
  - name: vip_leaseduration
    value: "15"
  - name: vip_renewdeadline
    value: "10"
  - name: vip_retryperiod
    value: "2"
  - name: vip_incluster
    value: "true"
  - name: vip_inCluster
    value: "true"
  - name: inCluster
    value: "true"
```

I know only the first of the three is the only right one, but I did it to really really make sure character casing and prefix stripping were not the culprit.

The error I get is:
```
panic: stat /etc/kubernetes/admin.conf: no such file or directory

goroutine 1 [running]:
github.com/plunder-app/kube-vip/pkg/cluster.NewManager(0x1d62e64, 0x1a, 0xc00000d000, 0x192b, 0x0, 0xc0001406e0, 0xc000143b80)
	/src/pkg/cluster/clusterLeader.go:59 +0x535
github.com/plunder-app/kube-vip/cmd.glob..func9(0x2ba0aa0, 0x3116750, 0x0, 0x0)
	/src/cmd/kube-vip-start.go:90 +0x1bf
github.com/spf13/cobra.(*Command).execute(0x2ba0aa0, 0x3116750, 0x0, 0x0, 0x2ba0aa0, 0x3116750)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2ba0d40, 0x4458ca, 0x2b3b740, 0xc000066778)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/plunder-app/kube-vip/cmd.Execute()
	/src/cmd/kube-vip.go:113 +0x31
main.main()
	/src/main.go:14 +0x6e
```

From what I read at `cmd/kube-vip-start.go` and `pkg/cluster/clusterLeader.go`, I really cannot get my head around why this is happening.
