### ISSUE TITLE
leaderElection is broken

### ISSUE THREAD

**Issue by guliaka** [plunder-app/kube-vip#116]
Followed instructions to build load-balanced control plane for Kubernetes cluster at [https://kube-vip.io/control-plane/](https://kube-vip.io/control-plane/).  

After deploying kube-vip to second node with config:  
``` yaml
  
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens192
    - name: vip_cidr
      value: "32"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: ###.###.###.###
    image: plndr/kube-vip:0.2.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
status: {}

```
I have in the log of this container:
2020-11-26T00:35:16.273397819Z time="2020-11-26T00:35:16Z" level=info msg="Beginning cluster membership, namespace [], lock name [plndr-cp-lock], id [vm-tst-kube-m2]"
2020-11-26T00:35:16.273668809Z I1126 00:35:16.273611       1 leaderelection.go:242] attempting to acquire leader lease  /plndr-cp-lock...
2020-11-26T00:35:16.273724134Z E1126 00:35:16.273688       1 leaderelection.go:321] error retrieving resource lock /plndr-cp-lock: an empty namespace may not be set when a resource name is provided
2020-11-26T00:35:18.101416084Z E1126 00:35:18.101292       1 leaderelection.go:321] error retrieving resource lock /plndr-cp-lock: an empty namespace may not be set when a resource name is provided
2020-11-26T00:35:20.058238179Z E1126 00:35:20.058099       1 leaderelection.go:321] error retrieving resource lock /plndr-cp-lock: an empty namespace may not be set when a resource name is provided
2020-11-26T00:35:21.383662919Z E1126 00:35:21.383536       1 leaderelection.go:321] error retrieving resource lock /plndr-cp-lock: an empty namespace may not be set when a resource name is provided
2020-11-26T00:35:23.153960632Z E1126 00:35:23.153842       1 leaderelection.go:321] error retrieving resource lock /plndr-cp-lock: an empty namespace may not be set when a resource name is provided
2020-11-26T00:35:25.314805828Z E1126 00:35:25.314693       1 leaderelection.go:321] error retrieving resource lock /plndr-cp-lock: an empty namespace may not be set when a resource name is provided
