### ISSUE TITLE
Latest build of kube-vip docker image does not start

### ISSUE THREAD

**Issue by guliaka** [plunder-app/kube-vip#121]
Have kube-vip in both roles in my kubernetes cluster, control plane HA - v0.2.2 and load-balancer v0.2.1. Was working till yesterday and now container does not start.

Here is my invocation for control plane:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - service
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens192
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "10"
    - name: vip_renewdeadline
      value: "5"
    - name: vip_retryperiod
      value: "2"
    - name: vip_address
      value: xxx.xxx.xxx.xxx
    image: plndr/kube-vip:0.2.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
status: {}
```

last output from container log:

level=fatal msg="error creating kubernetes client config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
