### ISSUE TITLE
Node name is not a DNS resolvable hostname in all cases

### ISSUE THREAD

**Issue by blinkiz** [plunder-app/kube-vip#133]
For some reason kube-vip for the control plane functionality is asking subnets DNS server what IP address the local nod/machine has. This is not the right behavior because DNS servers purpose is to resolve fully qualified domain names (FQDN), not hostnames.
```
E1215 08:31:28.853501       1 leaderelection.go:321] error retrieving resource lock kube-system/plunder-lock: Get "https://controller2:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plunder-lock": dial tcp: lookup controller2 on 192.168.38.4:53: no such host
E1215 08:31:30.634653       1 leaderelection.go:321] error retrieving resource lock kube-system/plunder-lock: Get "https://controller2:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plunder-lock": dial tcp: lookup controller2 on 192.168.38.4:53: no such host
```

For resolving hostnames there is no common rule among Linux distributions. CentOS does not resolve it by default. Ubuntu is resolving it to 127.0.1.1.
My recommendation is to ask kube-apiserver what IP address to do health check against.
`kubectl -n kube-system get pod kube-apiserver-controller2 -o json | jq .status.hostIP`

A workaround is to modify the manifest file and add so the pod can read `/etc/hosts` file where you can add an IP address for your local hostname.
Thanks for a great addition to the kubernetes ecosystem with vip-kube :slightly_smiling_face:

**Comment by thebsdbox** [comment]
Can you paste in your `vip.yaml` (remove anything that is confidential) :-) It looks like it's going down the resolve path.

**Comment by blinkiz** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens18
    - name: vip_cidr
      value: "32"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.38.10
    image: plndr/kube-vip:0.2.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/hosts
      name: hosts
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
  - hostPath:
      path: /etc/hosts
    name: hosts
status: {}
```
I have added volume for /etc/hosts file to get kube-vip to work.
