### ISSUE TITLE
Problems with BGP and 3 master nodes control plane

### ISSUE THREAD

**Issue by docbobo** [plunder-app/kube-vip#151]
**Describe the bug**
I am trying to set up a cluster with a control plane on 3 masters and an BGP assigned address. The cluster is being created with k3s. Everything is working with as long as only one of the nodes is being advertised to the peer router. Once the second master node joins in, things get somewhat weird and with the third one, everything just stops.

When it works, traceroute output looks like this

```
traceroute to 10.0.0.19 (10.0.0.19), 30 hops max, 60 byte packets
 1  unifi-usg (192.168.1.1)  3.478 ms  3.422 ms  3.396 ms
 2  k3s (10.0.0.19)  4.614 ms  4.585 ms  4.551 ms
```

When not, it looks like this or worse
```
traceroute to 10.0.0.19 (10.0.0.19), 30 hops max, 60 byte packets
 1  unifi-usg (192.168.1.1)  2.431 ms  2.380 ms  2.361 ms
 2  10.0.0.130 (10.0.0.130)  3.745 ms  3.728 ms *
 3  10.0.0.130 (10.0.0.130)  3065.146 ms !H  3065.129 ms !H  3065.114 ms !H
```

**To Reproduce**

Unifi USG Output
```
BGP table version is 0, local router ID is 10.0.0.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal,
              r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
* i10.0.0.19/32     10.0.0.132                    100      0 i
* i                 10.0.0.131                    100      0 i
*>i                 10.0.0.130                    100      0 i

```

```
BGP neighbor is 10.0.0.130, remote AS 64512, local AS 64512, internal link
  BGP version 4, remote router ID 10.0.0.130
  BGP state = Established, up for 00:08:08
  Last read 00:00:08, hold time is 90, keepalive interval is 30 seconds
  Neighbor capabilities:
    4 Byte AS: advertised and received
    Route refresh: advertised and received(new)
    Address family IPv4 Unicast: advertised and received
  Message statistics:
    Inq depth is 0
    Outq depth is 0
                         Sent       Rcvd
    Opens:                  7          0
    Notifications:          1          0
    Updates:                0          7
    Keepalives:           126        112
    Route Refresh:          0          0
    Capability:             0          0
    Total:                134        119
  Minimum time between advertisement runs is 5 seconds

 For address family: IPv4 Unicast
  Community attribute sent to this neighbor(both)
  1 accepted prefixes

  Connections established 7; dropped 6
  Last reset 00:08:30, due to Peer closed the session
Local host: 10.0.0.1, Local port: 179
Foreign host: 10.0.0.130, Foreign port: 35473
Nexthop: 10.0.0.1
Nexthop global: fe80::46d9:e7ff:fe95:e1db
Nexthop local: ::
BGP connection: non shared network
Read thread: on  Write thread: off

BGP neighbor is 10.0.0.131, remote AS 64512, local AS 64512, internal link
  BGP version 4, remote router ID 10.0.0.131
  BGP state = Established, up for 00:07:32
  Last read 00:00:02, hold time is 90, keepalive interval is 30 seconds
  Neighbor capabilities:
    4 Byte AS: advertised and received
    Route refresh: advertised and received(new)
    Address family IPv4 Unicast: advertised and received
  Message statistics:
    Inq depth is 0
    Outq depth is 0
                         Sent       Rcvd
    Opens:                  8          0
    Notifications:          1          0
    Updates:                2          8
    Keepalives:           130        114
    Route Refresh:          0          0
    Capability:             0          0
    Total:                141        122
  Minimum time between advertisement runs is 5 seconds

 For address family: IPv4 Unicast
  Community attribute sent to this neighbor(both)
  1 accepted prefixes

  Connections established 8; dropped 7
  Last reset 00:07:46, due to Peer closed the session
Local host: 10.0.0.1, Local port: 179
Foreign host: 10.0.0.131, Foreign port: 53739
Nexthop: 10.0.0.1
Nexthop global: fe80::46d9:e7ff:fe95:e1db
Nexthop local: ::
BGP connection: non shared network
Read thread: on  Write thread: off

BGP neighbor is 10.0.0.132, remote AS 64512, local AS 64512, internal link
  BGP version 4, remote router ID 10.0.0.132
  BGP state = Established, up for 00:06:51
  Last read 00:00:21, hold time is 90, keepalive interval is 30 seconds
  Neighbor capabilities:
    4 Byte AS: advertised and received
    Route refresh: advertised and received(new)
    Address family IPv4 Unicast: advertised and received
  Message statistics:
    Inq depth is 0
    Outq depth is 0
                         Sent       Rcvd
    Opens:                  8          0
    Notifications:          1          0
    Updates:                2          8
    Keepalives:           128        112
    Route Refresh:          0          0
    Capability:             0          0
    Total:                139        120
  Minimum time between advertisement runs is 5 seconds

 For address family: IPv4 Unicast
  Community attribute sent to this neighbor(both)
  1 accepted prefixes

  Connections established 8; dropped 7
  Last reset 00:07:08, due to Peer closed the session
Local host: 10.0.0.1, Local port: 179
Foreign host: 10.0.0.132, Foreign port: 42097
Nexthop: 10.0.0.1
Nexthop global: fe80::46d9:e7ff:fe95:e1db
Nexthop local: ::
BGP connection: non shared network
Read thread: on  Write thread: off
```

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.10
 - Kubernetes Version: v1.20+k3s2
 - Kube-vip Version: 0.3.0

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: vip_interface
          value: lo
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: bgp_enable
          value: "true"
        - name: bgp_routerinterface
          value: "eth0"
        - name: bgp_peers
          value: 10.0.0.1:64512::false
        - name: bgp_as
          value: "64512"
        - name: vip_address
          value: k3s
        image: plndr/kube-vip:0.3.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        value: server
        key: node.k3s.io/type
  updateStrategy: {}
```

**Additional context**
