### ISSUE TITLE
The VIP is lost when system-networkd restarts or when interface goes down/up

### ISSUE THREAD

**Issue by pradipd** [plunder-app/kube-vip#173]
**Describe the bug**
I'm on a cluster with a single node (i.e. control plane only) running kube-vip.
The k8s api-server becomes unreachable via the VIP after the following events:

1.  When networkd-systemd is restarted.  
2.  When the interface goes down/up.
3.  On Hyper-v, when running a mariner VM, if we save the VM, then restore the VM.

In all 3 cases, kube-vip logs show that the node is still master and still advertising the IP address.  I see the following messages in the log.
msg="Broadcasting ARP update for 172.16.254.0 (02:ee:00:00:00:00) via eth0"

**To Reproduce**
1. Bring up a k8s control plane with kube-vip
2. Do either:
   a. systemctl restart systemd-networkd
   b. ip link set eth0 down -- ip link set eth0 up
   c. save the vm -- restore the vm.

**Expected behavior**
I'd expect (or hope!) the k8s API-server would still be reachable after any of those events.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS/Distro: CBL_Mariner (https://github.com/microsoft/CBL-Mariner)
 - Kubernetes Version: v.1.18.8
 - Kube-vip Version: 0.1.8

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: eth0
    - name: vip_address
      value: 172.16.254.0
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    image: mocimages.azurecr.io/kube-vip:0.1.8
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
status: {}
```
**Additional context**
I understand that this may be a linux configuration issue.  However, I can't find any flags/settings that I'm supposed to set to make the above scenarios works.  Any help would be appreciated.

**Comment by thebsdbox** [comment]
The `kube-vip` pod will only apply networking configuration at the moment that it is elected as a leader, if anything changes that network configuration after that event then `kube-vip` wouldn't be aware of it. 

That being said it wouldn't be too difficult to perhaps have a timer that continually verifies that VIPs for HA and LoadBalancing actually exist. I'd love to hear your thoughts.

**Comment by thebsdbox** [comment]
Additionaly that version of kube-vip is waaaaay out of date. 0.2.0+ has a bunch of ARP fixes :-)

**Comment by pradipd** [comment]
Thanks for the info.  Will look at upgrading.

**Comment by thebsdbox** [comment]
Did you make any progress? Or identify anything specific that needs adding/fixing?

**Comment by pradipd** [comment]
Have not had a chance to look at it.  I have a few higher priority items I need to address. I'm hoping to get to it in mid-April.

**Comment by HubbeKing** [comment]
I can confirm this issue still exists in `0.3.2`, I've got the pod below deployed onto my control-plane nodes, all running k8s 1.20.5 and ubuntu 20.04 LTS. 
If the networking restarts on the currently elected leader, it loses the VIP. The kube-vip logs still claim that it's sending out ARP for the VIP, but it does not seem to get reassigned. 
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: enp2s0f1
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.1.100
    image: docker.io/plndr/kube-vip:0.3.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
