### ISSUE TITLE
AS per Rack

### ISSUE THREAD

**Issue by kplimack** [plunder-app/kube-vip#175]
Is there a way to configure a VIP that spans multiple racks in a layer 3 AS-per-rack model?

I see that I can configure a bgp peer, but I dont know how I would split this config to 3 pods that could schedule in a random AS.  It also does not look like I can supply multiple peers if were to provide a common HA pair of route reflectors in lieu of the ToR switch.   Perhaps I have not read deep enough into the docs, but I could not find a way to do this with kube-vip.

<img src="https://www.tigera.io/wp-content/uploads/2020/04/K8s-HA-ntwk-design.png" />

**Comment by thebsdbox** [comment]
Technically this should be possible, however stretching a cluster across nodes that have differs into network configurations comes with administrative overhead. We would need to label nodes and per rack with annotations so that kube-vip can identify the correct configuration.

**Comment by kplimack** [comment]
@thebsdbox if i already had a label on every node such as `rack=123`, what would be the next steps required?

**Comment by thebsdbox** [comment]
So equinix-metal have a cloud controller that will apply node annotations to each baremetal server that contains all the details of it's current rack:

We can see these annotations by describing on of the nodes:
```
kubectl describe node k8s.bgp02
{...}
Annotations:        
                    metal.equinix.com/node-asn: 65000
                    metal.equinix.com/peer-asn: 65530
                    metal.equinix.com/peer-ip: x.x.x.x
                    metal.equinix.com/src-ip: x.x.x.x
```
The `peer-ip` can be a comma separate value for multiple BGP peers, and you can see that these values are prefixed with a vendor (in this case `metal.equinix.com`). You would be able to do something similar by adding the correct node annotations "per rack" and using your own annotation prefix.

We could then apply the daemonset to just look up these values which would be pre-populated in the node annotations:
```
kube-vip manifest daemonset \
  --interface $INTERFACE \
  --services \
  --bgp \
  --annotations metal.equinix.com \
  --inCluster | k apply -f -
```

More details:

https://kube-vip.io/hybrid/daemonset/#equinix-metal-overview-(using-the-[equinix-metal-ccm](https://github.com/packethost/packet-ccm))
