### ISSUE TITLE
Additional parameter requires for toleration in DaemonSet

### ISSUE THREAD

**Issue by oskapt** [plunder-app/kube-vip#178]
**Describe the bug**

The DaemonSet manifest generates the following:

```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```

The default operator is "Equals" and without a value, this never matches. The Pods are never deployed. The corrected toleration is:

```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
```

kube-vip 0.3.2 on K3s 1.20.2+k3s1
