### ISSUE TITLE
KubeVIP Static Pod - Unable to find Namespace (serviceaccount mount missing)

### ISSUE THREAD

**Issue by camrossi** [plunder-app/kube-vip#183]
I have KubeVIP running perfectly fine on Ubuntu 18 with K8S 1.20.2
On Ubuntu 20 it does not work as it seems it can't find the Namespace. 
```
184 func returnNameSpace() (string, error) {
185     if data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace"); err == nil {
186         if ns := strings.TrimSpace(string(data)); len(ns) > 0 {
187             return ns, nil
188         }
189         return "", err
190     }
191     return "", fmt.Errorf("Unable to find Namespace")
```

My understanding is that Static Pod can't mount secrets so not sure how this is supposed to work. 
Am I missing something ?

**Comment by thebsdbox** [comment]
This is correct a static pod doesn't run "in" Kubernetes.. can you attach your kube-vip manifest so I can attempt to reproduce?

**Comment by camrossi** [comment]
Sorry for the delay. I use this manifest:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens192.4011
    - name: vip_cidr
      value: "32"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "50"
    - name: vip_renewdeadline
      value: "30"
    - name: vip_retryperiod
      value: "10"
    - name: vip_address
      value: 10.32.0.254
    image: plndr/kube-vip:latest
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
status: {}
```
In the logs, in the working cluster I see this:
root@fab2-k8s-1:~# docker logs 90a1c933c26e
time="2021-02-22T00:49:01Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [fab2-k8s-1]"
