### ISSUE TITLE
K3s script does not apply correctly

### ISSUE THREAD

**Issue by msnelling** [plunder-app/kube-vip#204]
**Describe the bug**
While following the [directions](https://kube-vip.io/control-plane/) for installing to k3s, the generated YAML does not apply and returns a `BadRequest` error.

**To Reproduce**
1. Generate the manifest `curl -sL kube-vip.io/k3s | vipAddress=192.168.0.40 vipInterface=eth0 sh | tee /tmp/vip.yaml`
2. Run ` kubectl apply -f /tmp/vip.yaml`
3. See error
```
Error from server (BadRequest): error when creating "/tmp/vip.yaml": DaemonSet in version "v1" cannot be handled as a DaemonSet: v1.DaemonSet.Spec: v1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true},{"nam|..., bigger context ...|gs":["manager"],"env":[{"name":"vip_arp","value":true},{"name":"vip_interface","value":"eth0"},{"nam|...
```

**Expected behavior**
The manifest should apply cleanly with no error.

**Environment (please complete the following information):**
 - OS/Distro: Photon OS 4.0
 - Kubernetes Version: v1.21.0
 - Kube-vip Version: From kube-vip.io/k3s

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: true
        - name: vip_interface
          value: eth0
        - name: port
          value: 6443
        - name: vip_cidr
          value: 32
        - name: cp_enable
          value: true
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: false
        - name: vip_address
          value: 192.168.0.40
        image: plndr/kube-vip:0.3.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Comment by ThomasADavis** [comment]
As crazy as this may sound..  put true in quotes.  aka, true => "true".

I don't know why it can't handle it otherwise..

an example:

```
        env:
          - name: vip_interface
            value: enp1s0
          - name: vip_arp
            value: "true"
          - name: port
```

It will also not work correctly, it's missing the serviceaccount, role and rolebinding information.

Here's what I am using on k3s v1.20+k31

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: kube-vip
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vip-role
  namespace: kube-system
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints"]
    verbs: ["watch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: vip-role-bind
subjects:
  - kind: ServiceAccount
    name: kube-vip
    apiGroup: ""
roleRef:
  kind: Role
  name: vip-role
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
          - name: vip_interface
            value: enp1s0
          - name: vip_arp
            value: "true"
          - name: port
            value: "6443"
          - name: vip_cidr
            value: "32"
          - name: cp_enable
            value: "true"
          - name: cp_namespace
            value: "kube-system"
          - name: svc_enable
            value: "false"
          - name: vip_address
            value: 192.168.1.242
        image: plndr/kube-vip:0.3.3
        imagePullPolicy: Always
        name: kube-vip
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```

it's a etcd cluster, so I bind kube-vip to just the master nodes.
